spring:
  application:
    name: playground1
  datasource:
    url: jdbc:mariadb://localhost:3306/playground
    username: root
    password: example

    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org:
      springframeword:
        jdbc:
          core: TRACE

